logging:
  pattern:
    dateformat: dd MMM yyyy HH:mm:ss
  level:
    com.onixbyte.cas:
      repository: debug

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

